/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwitterImageRouteImport } from './routes/twitter-image'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResumeInRouteImport } from './routes/resume-in'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as CvRouteImport } from './routes/cv'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiGithubLatestContributionsRouteImport } from './routes/api.github-latest-contributions'
import { Route as ApiGithubContributionsRouteImport } from './routes/api.github-contributions'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as BlogsSlugTwitterImageRouteImport } from './routes/blogs.$slug.twitter-image'
import { Route as BlogsSlugOpengraphImageRouteImport } from './routes/blogs.$slug.opengraph-image'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'

const TwitterImageRoute = TwitterImageRouteImport.update({
  id: '/twitter-image',
  path: '/twitter-image',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeInRoute = ResumeInRouteImport.update({
  id: '/resume-in',
  path: '/resume-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubLatestContributionsRoute =
  ApiGithubLatestContributionsRouteImport.update({
    id: '/api/github-latest-contributions',
    path: '/api/github-latest-contributions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubContributionsRoute = ApiGithubContributionsRouteImport.update({
  id: '/api/github-contributions',
  path: '/api/github-contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const BlogsSlugTwitterImageRoute = BlogsSlugTwitterImageRouteImport.update({
  id: '/twitter-image',
  path: '/twitter-image',
  getParentRoute: () => BlogsSlugRoute,
} as any)
const BlogsSlugOpengraphImageRoute = BlogsSlugOpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => BlogsSlugRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/cv': typeof CvRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/resume': typeof ResumeRoute
  '/resume-in': typeof ResumeInRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter-image': typeof TwitterImageRoute
  '/admin/new': typeof AdminNewRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-latest-contributions': typeof ApiGithubLatestContributionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/blogs/$slug': typeof BlogsSlugRouteWithChildren
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/blogs/$slug/opengraph-image': typeof BlogsSlugOpengraphImageRoute
  '/blogs/$slug/twitter-image': typeof BlogsSlugTwitterImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/cv': typeof CvRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/resume': typeof ResumeRoute
  '/resume-in': typeof ResumeInRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter-image': typeof TwitterImageRoute
  '/admin/new': typeof AdminNewRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-latest-contributions': typeof ApiGithubLatestContributionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/blogs/$slug': typeof BlogsSlugRouteWithChildren
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/blogs/$slug/opengraph-image': typeof BlogsSlugOpengraphImageRoute
  '/blogs/$slug/twitter-image': typeof BlogsSlugTwitterImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/cv': typeof CvRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/resume': typeof ResumeRoute
  '/resume-in': typeof ResumeInRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter-image': typeof TwitterImageRoute
  '/admin/new': typeof AdminNewRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-latest-contributions': typeof ApiGithubLatestContributionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/blogs/$slug': typeof BlogsSlugRouteWithChildren
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/blogs/$slug/opengraph-image': typeof BlogsSlugOpengraphImageRoute
  '/blogs/$slug/twitter-image': typeof BlogsSlugTwitterImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blogs'
    | '/cv'
    | '/opengraph-image'
    | '/resume'
    | '/resume-in'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/twitter-image'
    | '/admin/new'
    | '/api/github-contributions'
    | '/api/github-latest-contributions'
    | '/api/upload'
    | '/blogs/$slug'
    | '/admin/edit/$id'
    | '/blogs/$slug/opengraph-image'
    | '/blogs/$slug/twitter-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blogs'
    | '/cv'
    | '/opengraph-image'
    | '/resume'
    | '/resume-in'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/twitter-image'
    | '/admin/new'
    | '/api/github-contributions'
    | '/api/github-latest-contributions'
    | '/api/upload'
    | '/blogs/$slug'
    | '/admin/edit/$id'
    | '/blogs/$slug/opengraph-image'
    | '/blogs/$slug/twitter-image'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blogs'
    | '/cv'
    | '/opengraph-image'
    | '/resume'
    | '/resume-in'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/twitter-image'
    | '/admin/new'
    | '/api/github-contributions'
    | '/api/github-latest-contributions'
    | '/api/upload'
    | '/blogs/$slug'
    | '/admin/edit/$id'
    | '/blogs/$slug/opengraph-image'
    | '/blogs/$slug/twitter-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogsRoute: typeof BlogsRouteWithChildren
  CvRoute: typeof CvRoute
  OpengraphImageRoute: typeof OpengraphImageRoute
  ResumeRoute: typeof ResumeRoute
  ResumeInRoute: typeof ResumeInRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TwitterImageRoute: typeof TwitterImageRoute
  ApiGithubContributionsRoute: typeof ApiGithubContributionsRoute
  ApiGithubLatestContributionsRoute: typeof ApiGithubLatestContributionsRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twitter-image': {
      id: '/twitter-image'
      path: '/twitter-image'
      fullPath: '/twitter-image'
      preLoaderRoute: typeof TwitterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-in': {
      id: '/resume-in'
      path: '/resume-in'
      fullPath: '/resume-in'
      preLoaderRoute: typeof ResumeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-latest-contributions': {
      id: '/api/github-latest-contributions'
      path: '/api/github-latest-contributions'
      fullPath: '/api/github-latest-contributions'
      preLoaderRoute: typeof ApiGithubLatestContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-contributions': {
      id: '/api/github-contributions'
      path: '/api/github-contributions'
      fullPath: '/api/github-contributions'
      preLoaderRoute: typeof ApiGithubContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blogs/$slug/twitter-image': {
      id: '/blogs/$slug/twitter-image'
      path: '/twitter-image'
      fullPath: '/blogs/$slug/twitter-image'
      preLoaderRoute: typeof BlogsSlugTwitterImageRouteImport
      parentRoute: typeof BlogsSlugRoute
    }
    '/blogs/$slug/opengraph-image': {
      id: '/blogs/$slug/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/blogs/$slug/opengraph-image'
      preLoaderRoute: typeof BlogsSlugOpengraphImageRouteImport
      parentRoute: typeof BlogsSlugRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNewRoute: typeof AdminNewRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewRoute: AdminNewRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogsSlugRouteChildren {
  BlogsSlugOpengraphImageRoute: typeof BlogsSlugOpengraphImageRoute
  BlogsSlugTwitterImageRoute: typeof BlogsSlugTwitterImageRoute
}

const BlogsSlugRouteChildren: BlogsSlugRouteChildren = {
  BlogsSlugOpengraphImageRoute: BlogsSlugOpengraphImageRoute,
  BlogsSlugTwitterImageRoute: BlogsSlugTwitterImageRoute,
}

const BlogsSlugRouteWithChildren = BlogsSlugRoute._addFileChildren(
  BlogsSlugRouteChildren,
)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRouteWithChildren
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRouteWithChildren,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogsRoute: BlogsRouteWithChildren,
  CvRoute: CvRoute,
  OpengraphImageRoute: OpengraphImageRoute,
  ResumeRoute: ResumeRoute,
  ResumeInRoute: ResumeInRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TwitterImageRoute: TwitterImageRoute,
  ApiGithubContributionsRoute: ApiGithubContributionsRoute,
  ApiGithubLatestContributionsRoute: ApiGithubLatestContributionsRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
